language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "key-for-sblendorio-java-source-code"
    token:
      secure: bY2ToTWfxlnK8dtVcij9oqkohpV+EW9+YEfpjlYN8/aTDPzGqwqXPQZn4TcVYJE2aOxSLhCIvGQb967DmlWPtuXZhrVvAFtSl4qvjz6GRiZZ2/JH6NoZ+tEV2Ku3FiQg6suooDyh1Vp5sw8cr0Fj8v2j2/TG73bNeI0ELP74UuRK1cjwlzKR9D1p5XcfFhrRhvPG5U4WbrjKYBIA/zA2QhGcbZinlReCCltLo2c6a8TC6wKe2+u7WEbBOWkkICEVJObgsWwwXpBwFcsj0O9DnZ6kzQlrFpvN9wgO6405X/CloMWJ8wXWF/qBeBU+xz6hURtybRkLG9D86v/IivWfpCT1kvLophZY29NMRlpz2rXs1wZegM5sNYFMMr/NZ+NcCgE8EcCDIVx/f9jvRba6PtqTDKSDbUIvqejcFDt7jF6DugOe6fLda98ZITOeAWMHhrIZj0lmFsAJ15mMB0TunmQJ7ipAWLZxfM+soZ0jT+NTEqLXukvD6647t4ydbu6y87uK2W5cflJFdJ+S/6LKrMLpGYqPMcdgh7Vsx9CoVxkIKuCCArLluA4ZrCbdbVUjrlFuIiGxkxRZhIrMieQVRZmG0sf9cSeXppXFLficO3vx0FSoS1CegDCy4NkxeiSuY2cDuJQaTSJ5cuv+5CB4kvOaGvIrjKjbgiqbjTyJHAM=
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=sblendorio_petscii-bbs
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
